name: evaluate config

on:
  push:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: nix flake check (all hosts)
        run: nix flake check --all-systems
